server:
  port: 8001

spring:
  application:
    # 应用名称
    name: oauth2-resource-a-8001

# 自定义 jwt 配置（校验jwt）
jwt:
  cert-info:
    # 公钥证书存放位置
    public-key-location: myjks.cer
  claims:
    # 令牌的鉴发方：即授权服务器的地址
#    issuer: http://os.com:9000
    issuer: http://rookie-tuwer.server.com:9000
    # 令牌有效时间（单位：秒）；设为0时，和令牌实际时间一致。
    # 如果大于0，就是在原来过期时间的基础再加上这个值
    #expires-at: 0


# 配置 Eureka
eureka:
  client:
    # 默认值：true 需要从注册中心拉取其他的服务
    #fetch-registry: true
    service-url:
      # 注册中心地址
      defaultZone: http://localhost:7000/eureka/

  instance:
    # 修改Eureka上的默认描述信息
    instance-id: oauth2-resource-a-8001
    # 以IP地址注册到服务中心
    prefer-ip-address: true

# 监控端口配置
management:
  endpoints:
    web:
      exposure:
        # 开启 info,health；新版本中只默认开启了 health
        include: info,health
