server:
  forward-headers-strategy: framework
spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    version: openapi_3_1
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
